const x = '10'

//Try to re-assignment the value of de const x

try {
  x = 2
  console.log(`The new value of x is: ${x}`)
} catch (err) {
  console.log(`Error: ${err}`)
}

